sudo: false
language: node_js
node_js:
  - 6
script: npm run-script ci
cache:
  directories:
    - node_modules
env:
  - TRAVIS=1 MONGODB_VERSION=unstable MONGODB_TOPOLOGY=standalone
  - TRAVIS=1 MONGODB_VERSION=unstable MONGODB_TOPOLOGY=replicaset
